BUFFER_SIZE = 4096

# Message types
HELLO = "HELLO"
HELLO_REPLY = "HELLO_REPLY"
CHAT = "CHAT"
DISCOVER_SERVER = "DISCOVER_SERVER"
SERVER_INFO = "SERVER_INFO"

# Leader Election:

# to start the election
ELECTION = "ELECTION"
# higher node responds
ELECTION_OK = "ELECTION_OK"
# node declares itself leader
COORDINATOR = "COORDINATOR"
HEARTBEAT = "HEARTBEAT"


CLIENT_WHO_IS_LEADER = "CLIENT_WHO_IS_LEADER"
CLIENT_LEADER_INFO = "CLIENT_LEADER_INFO"
CLIENT_REDIRECT = "CLIENT_REDIRECT"
CHAT_ACK = "CHAT_ACK"

CLIENT_REGISTER = "CLIENT_REGISTER"
CLIENT_REGISTERED = "CLIENT_REGISTERED"
CHAT_DELIVER = "CHAT_DELIVER"



