BUFFER_SIZE = 4096

# Message types
HELLO = "HELLO"
HELLO_REPLY = "HELLO_REPLY"
CHAT = "CHAT"
DISCOVER_SERVER = "DISCOVER_SERVER"
SERVER_INFO = "SERVER_INFO"

# Leader Election
ELECTION = "ELECTION"
ELECTION_OK = "ELECTION_OK"
COORDINATOR = "COORDINATOR"
HEARTBEAT = "HEARTBEAT"

# Client / leader discovery
CLIENT_WHO_IS_LEADER = "CLIENT_WHO_IS_LEADER"
CLIENT_LEADER_INFO = "CLIENT_LEADER_INFO"
CLIENT_REDIRECT = "CLIENT_REDIRECT"

# Client registration
CLIENT_REGISTER = "CLIENT_REGISTER"
CLIENT_REGISTERED = "CLIENT_REGISTERED"
REGISTER_FWD = "REGISTER_FWD"

# Chat flow
CHAT_ACK = "CHAT_ACK"
CHAT_FWD = "CHAT_FWD"
CHAT_ACK_FWD = "CHAT_ACK_FWD"
CHAT_BCAST = "CHAT_BCAST"
CHAT_DELIVER = "CHAT_DELIVER"
